### ISSUE TITLE
regional offers accepted?

### ISSUE THREAD

**Issue by sknebel** [najela/discount-for-student-dev#1]
e.g. in Germany 1und1 has offerings that seem to be limited to German students. relevant for this list or not?

**Comment by zuron7** [comment]
Should be, maybe we should start a separate file for individual countries.

**Comment by najela** [comment]
@sknebel  It's relevant to the list and a PR will be welcomed. I support @zuron7's idea for creating a separate file for each country but we could do that eventually when we get a lot  of discounts which are limited to a particular country.

**Comment by arthurvr** [comment]
:+1: Sounds like a good idea! @najela Awesome list, by the way!

**Comment by najela** [comment]
Thanks @arthurvr

**Comment by najela** [comment]
fping @sknebel
