### ISSUE TITLE
License is weird

### ISSUE THREAD

**Issue by strugee** [najela/discount-for-student-dev#11]
At the bottom of the README, in the license block, is the text: "the underlying source code used to format and display that content is licensed under the MIT license."

That doesn't make sense, though, given that there's only two files in the repo and one branch. PR?

**Comment by najela** [comment]
Well I considered the https://github.com/najela/discount-for-student-dev/blob/master/README.md as `code`

**Comment by strugee** [comment]
I wouldn't. But OK.

In that case, what exactly is CC? The HTML output...?

**Comment by najela** [comment]
@strugee Content and source code are different to me. 

Okay do you consider HTML as `code`?

Content = CC
Code used to format content (Markdown) = MIT

I don't know if that makes sense to you?

**Comment by strugee** [comment]
Content and source code are different to me, too.

That makes sense to me, but I was thinking about it very differently from you. The way I was looking at it was the Markdown and HTML being the same (content), and there being no code at all. To me, the HTML and the Markdown aren't different. They're the same thing in a different form.

I define content as "stuff for humans", so e.g. prose, images, etc. Content is abstract so it has to be encapsulated in some format, like HTML, Markdown, ODT, etc. Whereas code is Ruby or Python or C or whatever.

That's the way I see it. You may still disagree, in which case you might consider clarifying.

**Comment by najela** [comment]
@strugee Okay man, I'll keep this PR open while I think about restructuring the liscense

**Comment by strugee** [comment]
@najela I mean, it's your project, so you're free to license it however you want. I'm just letting you know that your wording is confusing to some of us :)

**Comment by arthurvr** [comment]
Just use something like https://github.com/sindresorhus/awesome#license but replace the name ;)

**Comment by najela** [comment]
Fixed by https://github.com/najela/discount-for-student-dev/commit/41d2eea3f9f563c68c8dde81a311312e8ec51155 Thanks @arthurvr
