### ISSUE TITLE
Add `contributing.md`

### ISSUE THREAD

**Issue by arthurvr** [najela/discount-for-student-dev#9]
Maybe you should consider adding a `contributing.md` file in the repo?

You can find some inspriation in this repo: https://github.com/sindresorhus/awesome/blob/master/contributing.md

**Comment by najela** [comment]
Thanks @arthurvr I'll work on it

**Comment by najela** [comment]
Fixed https://github.com/najela/discount-for-student-dev/commit/d4902420e16fbf65a741eea7f7a3ece8391931a4
